# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_methods.grpc_bin.survey6_pb2 as survey6__pb2


class ClientConnectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientConnect = channel.unary_unary(
                '/survey6.ClientConnection/ClientConnect',
                request_serializer=survey6__pb2.ClientConnectRequest.SerializeToString,
                response_deserializer=survey6__pb2.ClientConnectResponse.FromString,
                )
        self.ClientDisconnect = channel.unary_unary(
                '/survey6.ClientConnection/ClientDisconnect',
                request_serializer=survey6__pb2.ClientDisconnectRequest.SerializeToString,
                response_deserializer=survey6__pb2.ClientDisconnectResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/survey6.ClientConnection/Heartbeat',
                request_serializer=survey6__pb2.HeartbeatSender.SerializeToString,
                response_deserializer=survey6__pb2.HeartbeatAck.FromString,
                )
        self.GrantReceiveData = channel.unary_unary(
                '/survey6.ClientConnection/GrantReceiveData',
                request_serializer=survey6__pb2.GrantReceiveDataRequest.SerializeToString,
                response_deserializer=survey6__pb2.GrantReceiveDataResponse.FromString,
                )


class ClientConnectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientDisconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantReceiveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientConnectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientConnect,
                    request_deserializer=survey6__pb2.ClientConnectRequest.FromString,
                    response_serializer=survey6__pb2.ClientConnectResponse.SerializeToString,
            ),
            'ClientDisconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientDisconnect,
                    request_deserializer=survey6__pb2.ClientDisconnectRequest.FromString,
                    response_serializer=survey6__pb2.ClientDisconnectResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=survey6__pb2.HeartbeatSender.FromString,
                    response_serializer=survey6__pb2.HeartbeatAck.SerializeToString,
            ),
            'GrantReceiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantReceiveData,
                    request_deserializer=survey6__pb2.GrantReceiveDataRequest.FromString,
                    response_serializer=survey6__pb2.GrantReceiveDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'survey6.ClientConnection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientConnection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.ClientConnection/ClientConnect',
            survey6__pb2.ClientConnectRequest.SerializeToString,
            survey6__pb2.ClientConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClientDisconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.ClientConnection/ClientDisconnect',
            survey6__pb2.ClientDisconnectRequest.SerializeToString,
            survey6__pb2.ClientDisconnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.ClientConnection/Heartbeat',
            survey6__pb2.HeartbeatSender.SerializeToString,
            survey6__pb2.HeartbeatAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GrantReceiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.ClientConnection/GrantReceiveData',
            survey6__pb2.GrantReceiveDataRequest.SerializeToString,
            survey6__pb2.GrantReceiveDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class UtilsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ViewHealthOfClient = channel.unary_unary(
                '/survey6.Utils/ViewHealthOfClient',
                request_serializer=survey6__pb2.ViewHealthRequest.SerializeToString,
                response_deserializer=survey6__pb2.ViewHealthResponse.FromString,
                )
        self.ViewDataRecieved = channel.unary_unary(
                '/survey6.Utils/ViewDataRecieved',
                request_serializer=survey6__pb2.ViewDataRecievedRequest.SerializeToString,
                response_deserializer=survey6__pb2.ViewDataRecievedResponse.FromString,
                )


class UtilsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ViewHealthOfClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewDataRecieved(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UtilsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ViewHealthOfClient': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewHealthOfClient,
                    request_deserializer=survey6__pb2.ViewHealthRequest.FromString,
                    response_serializer=survey6__pb2.ViewHealthResponse.SerializeToString,
            ),
            'ViewDataRecieved': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewDataRecieved,
                    request_deserializer=survey6__pb2.ViewDataRecievedRequest.FromString,
                    response_serializer=survey6__pb2.ViewDataRecievedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'survey6.Utils', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Utils(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ViewHealthOfClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.Utils/ViewHealthOfClient',
            survey6__pb2.ViewHealthRequest.SerializeToString,
            survey6__pb2.ViewHealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ViewDataRecieved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/survey6.Utils/ViewDataRecieved',
            survey6__pb2.ViewDataRecievedRequest.SerializeToString,
            survey6__pb2.ViewDataRecievedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
